name: Build and push containers

on:
  release:
    types: [published]

jobs:
  release-container:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Compile tag list
        id: tags
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PREFIX=ghcr.io/laminas/automatic-releases
          MAJOR="${PREFIX}:$(echo ${TAG} | cut -d. -f1)"
          MINOR="${MAJOR}.$(echo ${TAG} | cut -d. -f2)"
          PATCH="${PREFIX}:${TAG}"
          echo "::set-output name=tags::[\"${MAJOR}\",\"${MINOR}\",\"${PATCH}\"]"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ join(fromJSON(steps.tags.outputs.tags), ',') }}
